---
name: Sample123
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: email123
enabled: true
trigger:
  type: email123.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: vm create
    type: contains
action:
  ref: azure_vm.create_vm
  parameters:
    Subcription_id: '2f50f202-0a84-4c8c-a929-fcc5a3174590'
    Group_Name: '{{trigger.group}}'
    Location: '{{trigger.location}}'
    VM_Name: '{{trigger.vmname}}'
    Client_Id: '7aae3fd9-9324-463f-89f5-7c4144971bfb'
    Secret: 'MJOJszdQ2fl]xYQQ5Lm+]hAM2vgR0e+5'
    Tenant_Id:  'd5656af4-b7b3-45b9-9346-fb0547921fb7'    
  ref: core.local 
  parameters:
    cmd: echo hello world 
